name: ColorAPI
version: '${project.version}'
main: com.github.colorapi.ColorAPIPlugin
api-version: '1.16'

author: Echo24h
description: A plugin API to allow players to create custom color codes

permissions:
  colorapi.reload:
    description: Allows you to reload ColorAPI plugin
    default: op
  colorapi.*:
    description: Wildcard permission
    default: op
    children:
      - colorapi.reload: true

commands:
  colorapi:
    subcommands:
      reload:
        description: Reload ColorAPI plugin
        usage: /<command> reload
        permission: colorapi.reload